### ISSUE TITLE
Exceptions on iOS in background threads are not being reported

### ISSUE THREAD

**Issue by mattleibow** [MindscapeHQ/raygun4maui#12]
I noticed this when using threads other than the main/UI thread.

```cs
var thread = new Thread(() =>
{
    throw new InvalidOperationException("From a new thread.");
});
thread.Start();
```

> Starting a new thread is probably not the best thing to do in a mobile app, but I am trying to check a few things.

**Comment by ProRedCat** [comment]
This should be fixed in our 1.4.2-pre-1 release for Raygun4Maui https://www.nuget.org/packages/Raygun4Maui/1.4.2-pre-1
