### ISSUE TITLE
Docs: Enum defaults to true

### ISSUE THREAD

**Issue by breyed** [MindscapeHQ/raygun4maui#14]
The README has:
```
Raygun4MauiSettings raygunMauiSettings = new Raygun4MauiSettings {
    // ...
    MinLogLevel = LogLevel.Debug, // defaults to true
    MaxLogLevel = LogLevel.Critical // defaults to true
};
```

`MinLogLevel` and `MaxLogLevel` are enums. Saying "defaults to true" doesn't make any sense.

The same issue is in the [Raygun MAUI docs](https://raygun.com/documentation/language-guides/dotnet/crash-reporting/maui/).

**Comment by ProRedCat** [comment]
This should be addressed in Raygun4Maui 2.0.0 which will be out soon. Thanks for pointing that out!
